{% set name = "plyvel" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd918e0b31690abcd3d202a8742caf951ab2fe1573de7af71c38456847f9202b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - setuptools
    - wheel
    - python
    - leveldb 1.23
  run:
    - python
    - leveldb

test:
  requires:
    - pip
  imports:
    - plyvel
  commands:
    - pip check

about:
  home: https://github.com/wbolster/plyvel
  dev_url: https://github.com/wbolster/plyvel
  doc_url: https://plyvel.readthedocs.io/
  summary: Plyvel, a fast and feature-rich Python interface to LevelDB
  description: |
    Plyvel is a fast and feature-rich Python interface to LevelDB.
    Plyvel has a rich feature set, high performance, and a friendly Pythonic API.
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
