{% set name = "plyvel" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3caf6009e4fc24fbf8712d3f5ef3da7e56495c26a488df2161218fc34e46019c

build:
  number: 0
  # 3.12 support introduced in 1.5.1: https://github.com/wbolster/plyvel/blob/main/NEWS.rst#plyvel-151
  skip: True  # [py<36 or py>312]
  script:
    - cython --cplus --fast-fail --annotate plyvel/_plyvel.pyx -vv
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cython >=0.17
  host:
    - pip
    - setuptools
    - wheel
    - python
    - leveldb {{ leveldb }}
  run:
    - python
    - {{ pin_compatible('leveldb', max_pin='x.x') }}

test:
  source_files:
    - test
  requires:
    - pip
    - pytest >=3.6
  imports:
    - plyvel
  commands:
    - pip check
    - pytest -vv test                                   # [osx]
    # This test expects no permissions to /tmp dir, but linux instances run under root
    # Incompatible path on windows
    - pytest -vv test -k "not test_open_read_only_dir"  # [linux or win]

about:
  home: https://github.com/wbolster/plyvel
  dev_url: https://github.com/wbolster/plyvel
  doc_url: https://plyvel.readthedocs.io
  summary: Plyvel, a fast and feature-rich Python interface to LevelDB
  description: |
    Plyvel is a fast and feature-rich Python interface to LevelDB.
    Plyvel has a rich feature set, high performance, and a friendly Pythonic API.
  license: BSD-3-Clause
  license_file: LICENSE.rst
  license_family: BSD

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
